In [30]:
#  Memuat data dari file CSV
import pandas as pd
#  Memuat data dari file CSV ke dalam DataFrame
df = pd.read_csv('movie_sample_dataset.csv')

In [31]:
# Menampilkan beberapa baris pertama dari DataFrame untuk verifikasi
df.head()

,color,director_name,duration,gross,genres,movie_title,title_year,language,country,budget,imdb_score,actors,movie_facebook_likes
0,Color,Martin Scorsese,240,116866727.0,Biography|Comedy|Crime|Drama,The Wolf of Wall Street,2013,English,USA,100000000.0,8.2,"Leonardo DiCaprio,Matthew McConaughey,Jon Favreau",138000
1,Color,Shane Black,195,408992272.0,Action|Adventure|Sci-Fi,Iron Man 3,2013,English,USA,200000000.0,7.2,"Robert Downey Jr.,Jon Favreau,Don Cheadle",95000
2,color,Quentin Tarantino,187,54116191.0,Crime|Drama|Mystery|Thriller|Western,The Hateful Eight,2015,English,USA,44000000.0,7.9,"Craig Stark,Jennifer Jason Leigh,Zoë Bell",114000
3,Color,Kenneth Lonergan,186,46495.0,Drama,Margaret,2011,English,usa,14000000.0,6.5,"Matt Damon,Kieran Culkin,John Gallagher Jr.",0
4,Color,Peter Jackson,186,258355354.0,Adventure|Fantasy,The Hobbit: The Desolation of Smaug,2013,English,USA,225000000.0,7.9,"Aidan Turner,Adam Brown,James Nesbitt",83000

In [32]:
# Periksa informasi umum tentang dataset, termasuk tipe data dan nilai yang hilang.
df.info()
df.isnull().sum()
df['color'].value_counts() # call value_counts() on the seraies

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   color                 88 non-null     object
 1   director_name         88 non-null     object
 2   duration              99 non-null     int64
 3   gross                 91 non-null     float64
 4   genres                98 non-null     object
 5   movie_title           99 non-null     object
 6   title_year            99 non-null     int64
 7   language              99 non-null     object
 8   country               99 non-null     object
 9   budget                95 non-null     float64
 10  imdb_score            99 non-null     float64
 11  actors                99 non-null     object
 12  movie_facebook_likes  99 non-null     int64
dtypes: float64(3), int64(3), object(7)
memory usage: 10.2+ KB

color
Color               86
color                1
 Black and White     1
Name: count, dtype: int64

In [33]:
# Hapus baris yang memiliki nilai NaN di kolom 'gross' dan 'budget'
df_cleaned = df.dropna(subset=["gross"], axis=0, inplace=True)
df_cleaned = df.dropna(subset=["budget"], axis=0, inplace=True)

# Periksa kembali jumlah nilai yang hilang
df_cleaned = df.reset_index(drop=True)
df_cleaned.isnull().sum()
df

,color,director_name,duration,gross,genres,movie_title,title_year,language,country,budget,imdb_score,actors,movie_facebook_likes
0,Color,Martin Scorsese,240,116866727.0,Biography|Comedy|Crime|Drama,The Wolf of Wall Street,2013,English,USA,100000000.0,8.2,"Leonardo DiCaprio,Matthew McConaughey,Jon Favreau",138000
1,Color,Shane Black,195,408992272.0,Action|Adventure|Sci-Fi,Iron Man 3,2013,English,USA,200000000.0,7.2,"Robert Downey Jr.,Jon Favreau,Don Cheadle",95000
2,color,Quentin Tarantino,187,54116191.0,Crime|Drama|Mystery|Thriller|Western,The Hateful Eight,2015,English,USA,44000000.0,7.9,"Craig Stark,Jennifer Jason Leigh,Zoë Bell",114000
3,Color,Kenneth Lonergan,186,46495.0,Drama,Margaret,2011,English,usa,14000000.0,6.5,"Matt Damon,Kieran Culkin,John Gallagher Jr.",0
4,Color,Peter Jackson,186,258355354.0,Adventure|Fantasy,The Hobbit: The Desolation of Smaug,2013,English,USA,225000000.0,7.9,"Aidan Turner,Adam Brown,James Nesbitt",83000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,Color,Tony Gilroy,135,113165635.0,Action|Adventure|Thriller,The Bourne Legacy,2012,English,USA,125000000.0,6.7,"Jeremy Renner,Scott Glenn,Stacy Keach",31000
94,Color,Steve McQueen,134,56667870.0,Biography|Drama|History,12 Years a Slave,2013,English,USA,20000000.0,8.1,"Quvenzhané Wallis,Scoot McNairy,Taran Killam",83000
96,Color,Paul Greengrass,134,107100855.0,Biography|Drama|Thriller,Captain Phillips,2013,English,USA,55000000.0,7.9,"Tom Hanks,Chris Mulkey,Michael Chernus",65000
97,Color,David Ayer,134,85707116.0,Action|Drama|War,Fury,2014,English,USA,68000000.0,7.6,"Brad Pitt,Logan Lerman,Jim Parrack",82000
98,Color,Clint Eastwood,5,47034272.0,Biography|Drama|Music|Musical,Jersey Boys,2014,English,USA,40000000.0,6.9,"Johnny Cannizzaro,Steve Schirripa,Scott Vance",16000

In [34]:
# Atasi nilai yang tidak konsisten atau kesalahan penulisan di kolom, seperti perbedaan antara "Color" dan "color". Ubah semua nilai di kolom 'color'menjadi huruf kecil
df['color'] = df['color'].str.lower()

# Periksa kembali nilai unik di kolom 'color'
print(df['color'].unique())

['color' 'color ' nan ' black and white']

In [35]:
# prompt: Ubah atau hapus nilai-nilai yang tidak standar, seperti nilai negatif atau "N/A".

# Mengganti nilai negatif di kolom 'budget' dan 'gross' dengan NaN
df.loc[df['budget'] < 0, 'budget'] = float('nan')
df.loc[df['gross'] < 0, 'gross'] = float('nan')

# Menghapus baris dengan nilai NaN di kolom 'budget' dan 'gross'
df.dropna(subset=['budget', 'gross'], inplace=True)

# Me-reset index setelah menghapus baris
df.reset_index(drop=True, inplace=True)

# Menampilkan beberapa baris pertama dari DataFrame yang telah dibersihkan
df.head()

,color,director_name,duration,gross,genres,movie_title,title_year,language,country,budget,imdb_score,actors,movie_facebook_likes
0,color,Martin Scorsese,240,116866727.0,Biography|Comedy|Crime|Drama,The Wolf of Wall Street,2013,English,USA,100000000.0,8.2,"Leonardo DiCaprio,Matthew McConaughey,Jon Favreau",138000
1,color,Shane Black,195,408992272.0,Action|Adventure|Sci-Fi,Iron Man 3,2013,English,USA,200000000.0,7.2,"Robert Downey Jr.,Jon Favreau,Don Cheadle",95000
2,color,Quentin Tarantino,187,54116191.0,Crime|Drama|Mystery|Thriller|Western,The Hateful Eight,2015,English,USA,44000000.0,7.9,"Craig Stark,Jennifer Jason Leigh,Zoë Bell",114000
3,color,Kenneth Lonergan,186,46495.0,Drama,Margaret,2011,English,usa,14000000.0,6.5,"Matt Damon,Kieran Culkin,John Gallagher Jr.",0
4,color,Peter Jackson,186,258355354.0,Adventure|Fantasy,The Hobbit: The Desolation of Smaug,2013,English,USA,225000000.0,7.9,"Aidan Turner,Adam Brown,James Nesbitt",83000

In [36]:
# Melihat type data
df.dtypes
#Ubah tipe data kolom menjadi tipe data yang sesuai (misalnya, konversi budget dan gross menjadi numerik).
df["gross"] = df["gross"].astype(int)
df["budget"] = df["budget"].astype(int)
df.dtypes

color                    object
director_name            object
duration                  int64
gross                     int64
genres                   object
movie_title              object
title_year                int64
language                 object
country                  object
budget                    int64
imdb_score              float64
actors                   object
movie_facebook_likes      int64
dtype: object

In [37]:
# Memisahkan genre yang digabungkan menjadi beberapa kolom terpisah
df['genres'] = df['genres'].str.split('|')
df = df.explode('genres')

# Menampilkan beberapa baris pertama dari DataFrame yang telah dipisahkan
df.head()

,color,director_name,duration,gross,genres,movie_title,title_year,language,country,budget,imdb_score,actors,movie_facebook_likes
0,color,Martin Scorsese,240,116866727,Biography,The Wolf of Wall Street,2013,English,USA,100000000,8.2,"Leonardo DiCaprio,Matthew McConaughey,Jon Favreau",138000
0,color,Martin Scorsese,240,116866727,Comedy,The Wolf of Wall Street,2013,English,USA,100000000,8.2,"Leonardo DiCaprio,Matthew McConaughey,Jon Favreau",138000
0,color,Martin Scorsese,240,116866727,Crime,The Wolf of Wall Street,2013,English,USA,100000000,8.2,"Leonardo DiCaprio,Matthew McConaughey,Jon Favreau",138000
0,color,Martin Scorsese,240,116866727,Drama,The Wolf of Wall Street,2013,English,USA,100000000,8.2,"Leonardo DiCaprio,Matthew McConaughey,Jon Favreau",138000
1,color,Shane Black,195,408992272,Action,Iron Man 3,2013,English,USA,200000000,7.2,"Robert Downey Jr.,Jon Favreau,Don Cheadle",95000

In [38]:
# prompt: normalisasi teks untuk memastikan konsistensi

# Import library yang dibutuhkan
import re

# Fungsi untuk normalisasi teks
def normalize_text(text):
  """
  Fungsi untuk normalisasi teks dengan mengubah teks menjadi huruf kecil,
  menghapus karakter khusus, dan menghilangkan spasi berlebih.

  Args:
    text: Teks yang akan dinormalisasi.

  Returns:
    Teks yang telah dinormalisasi.
  """
  if isinstance(text, str):  # Periksa apakah input adalah string
    text = text.lower()  # Ubah teks menjadi huruf kecil
    text = re.sub(r'[^\w\s]', '', text)  # Hapus karakter khusus
    text = re.sub(r'\s+', ' ', text).strip()  # Hapus spasi berlebih
    return text
  else:
    return text

# Contoh penerapan normalisasi teks pada kolom 'plot_keywords'
df['director_name'] = df['director_name'].apply(normalize_text)
df['genres'] = df['genres'].apply(normalize_text)
df['movie_title'] = df['movie_title'].apply(normalize_text)
df['language'] = df['language'].apply(normalize_text)
df['actors'] = df['actors'].apply(normalize_text)
# Menampilkan beberapa baris pertama dari DataFrame dengan kolom yang telah dinormalisasi
df.head()

,color,director_name,duration,gross,genres,movie_title,title_year,language,country,budget,imdb_score,actors,movie_facebook_likes
0,color,martin scorsese,240,116866727,biography,the wolf of wall street,2013,english,USA,100000000,8.2,leonardo dicapriomatthew mcconaugheyjon favreau,138000
0,color,martin scorsese,240,116866727,comedy,the wolf of wall street,2013,english,USA,100000000,8.2,leonardo dicapriomatthew mcconaugheyjon favreau,138000
0,color,martin scorsese,240,116866727,crime,the wolf of wall street,2013,english,USA,100000000,8.2,leonardo dicapriomatthew mcconaugheyjon favreau,138000
0,color,martin scorsese,240,116866727,drama,the wolf of wall street,2013,english,USA,100000000,8.2,leonardo dicapriomatthew mcconaugheyjon favreau,138000
1,color,shane black,195,408992272,action,iron man 3,2013,english,USA,200000000,7.2,robert downey jrjon favreaudon cheadle,95000

In [39]:
# Simpan data yang telah diproses ke dalam file CSV baru dengan nama movie_dataset_cleaned.csv.
df.to_csv('movie_dataset_cleaned1.csv', index=False)